version: '3.8'

services:
  inference:
    build:
      context: ./inference
      dockerfile: Dockerfile
    container_name: inference_service
    ports:
      - "8001:8001"

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api_service
    ports:
      - "8000:8000"
    depends_on:
      - inference
    environment:
      - INFERENCE_URL=http://inference:8001/inference/

  runner:
    build:
      context: ./runner
      dockerfile: Dockerfile
    container_name: runner_service
    ports:
      - "7878:7878"
    depends_on:
      - inference

  orchestrator:
    build:
      context: ./orchestrator
      dockerfile: Dockerfile
    container_name: orchestrator
    ports:
      - "1612:1612"
    depends_on:
      - inference
      - runner
      - api

    # pg-1 for orh

    
    # pg-2 for api
