version: '3.8'

networks:
  app-tier:
    driver: bridge

services:
  kafka:
    image: bitnami/kafka:4.0
    container_name: kafka
    networks:
      - app-tier
    ports:
      - "9092:9092"
    environment:
      # KRaft mode
      KAFKA_CFG_KRAFT_MODE: "true"
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      # Listener configuration
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      # Kraft: must initialize metadata at first run
      KAFKA_ENABLE_KRAFT: "yes"

      # Optional
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"

    restart: unless-stopped
    # healthcheck:
    #   test: ["CMD-SHELL", "kafka-topics.sh", "--bootstrap-server",  "kafka:9092", "--topic", "test", "--create", "--if-not-exists", "&&", "kafka-topics.sh", "--bootstrap-server", "kafka:9092", "--topic", "test", "--describe"]
    #   interval: 30s
    #   timeout: 30s
    #   retries: 5
    #   start_period: 30s

  # postgres
  pg_orchestrator:
    image: postgres:15
    container_name: pg_orchestrator
    networks:
      - app-tier
    environment:
      POSTGRES_DB: orchestrator_db
      POSTGRES_USER: orchestrator_user
      POSTGRES_PASSWORD: orchestrator_pass
    ports:
      - "5433:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "ls"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s

  pg_runner:
    image: postgres:15
    container_name: pg_runner
    networks:
      - app-tier
    environment:
      POSTGRES_DB: runner_db
      POSTGRES_USER: runner_user
      POSTGRES_PASSWORD: runner_pass
    ports:
      - "5435:5432"
    restart: unless-stopped

  # services
  orchestrator:
    build:
      context: ./orchestrator
      dockerfile: Dockerfile
    container_name: orchestrator
    networks:
      - app-tier
    volumes:
      - ./shared:/app/shared
    ports:
      - "1612:1612"
    depends_on: 
      - pg_orchestrator
        # condition: service_healthy
      - kafka
        # condition: service_healthy
    environment:
      POSTGRES_HOST: pg_orchestrator
      POSTGRES_PORT: 5432
      POSTGRES_DB: orchestrator_db
      POSTGRES_USER: orchestrator_user
      POSTGRES_PASSWORD: orchestrator_pass
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api_service
    networks:
      - app-tier
    volumes:
      - ./shared:/app/shared
    ports:
      - "8000:8000"
    depends_on:
      - kafka
      - orchestrator
    environment:
      SERVICE_PORT: 8000
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092


  runner:
    build:
      context: ./runner
      dockerfile: Dockerfile
    deploy:
        replicas: 3
    networks:
      - app-tier
    volumes:
      - ./shared:/app/shared
    depends_on:
      - kafka
      - inference
      - pg_runner
    environment:
      POSTGRES_HOST: pg_runner
      POSTGRES_DB: runner_db
      POSTGRES_USER: runner_user
      POSTGRES_PASSWORD: runner_pass
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  inference:
    build:
      context: ./inference
      dockerfile: Dockerfile
    deploy:
        replicas: 3
    depends_on:
      - kafka
    networks:
      - app-tier
    volumes:
      - ./shared:/app/shared
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
